# Generated by Django 4.0.4 on 2022-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='г.Красноярск', max_length=100)),
                ('street', models.CharField(default='ул. Красноярская', max_length=100)),
                ('building', models.CharField(default='22', max_length=100)),
                ('phone_number', models.CharField(default='9999999999', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('postcode', models.CharField(default='660125', max_length=6)),
                ('opening_hours', models.TimeField(default='09:00')),
                ('closing_hours', models.TimeField(default='20:00')),
            ],
        ),
    ]
