# Generated by Django 4.0.4 on 2022-06-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DryCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_object', models.CharField(default=None, max_length=50)),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Легковой'), (2, 'Универсал'), (3, 'Паркетник минивэн'), (4, 'Внедорожник'), (5, 'Микроавтобус')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalWashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_object', models.CharField(default=None, max_length=50)),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Легковой'), (2, 'Универсал'), (3, 'Паркетник минивэн'), (4, 'Внедорожник'), (5, 'Микроавтобус')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='InternalWashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_object', models.CharField(default=None, max_length=50)),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Легковой'), (2, 'Универсал'), (3, 'Паркетник минивэн'), (4, 'Внедорожник'), (5, 'Микроавтобус')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Polishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_object', models.CharField(default=None, max_length=50)),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Легковой'), (2, 'Универсал'), (3, 'Паркетник минивэн'), (4, 'Внедорожник'), (5, 'Микроавтобус')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
