# Generated by Django 4.0.4 on 2022-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drycleaning',
            old_name='wash_object',
            new_name='washing_object',
        ),
        migrations.RenameField(
            model_name='externalwashing',
            old_name='wash_object',
            new_name='washing_object',
        ),
        migrations.RenameField(
            model_name='internalwashing',
            old_name='wash_object',
            new_name='washing_object',
        ),
        migrations.RenameField(
            model_name='polishing',
            old_name='wash_object',
            new_name='washing_object',
        ),
        migrations.RemoveField(
            model_name='drycleaning',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='drycleaning',
            name='price',
        ),
        migrations.RemoveField(
            model_name='externalwashing',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='externalwashing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='internalwashing',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='internalwashing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='polishing',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='polishing',
            name='price',
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='light_weight_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='minibus_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='minivan_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='suv_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='universal_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalwashing',
            name='light_weight_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalwashing',
            name='minibus_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalwashing',
            name='minivan_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalwashing',
            name='suv_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalwashing',
            name='universal_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='internalwashing',
            name='light_weight_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='internalwashing',
            name='minibus_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='internalwashing',
            name='minivan_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='internalwashing',
            name='suv_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='internalwashing',
            name='universal_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='polishing',
            name='light_weight_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='polishing',
            name='minibus_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='polishing',
            name='minivan_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='polishing',
            name='suv_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='polishing',
            name='universal_car_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
