# Generated by Django 4.0.4 on 2022-06-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=50, verbose_name='Марка')),
                ('model', models.CharField(default=None, max_length=50, verbose_name='Модель')),
                ('engine', models.CharField(default=None, max_length=50, verbose_name='Двигатель')),
                ('transmission', models.CharField(default=None, max_length=50, verbose_name='Коробка передач')),
                ('steering_wheel', models.PositiveSmallIntegerField(choices=[(1, 'Левый'), (2, 'Правый')])),
                ('wheel_drive_type', models.PositiveSmallIntegerField(choices=[(1, 'Передний'), (2, 'Задний'), (3, 'Полный')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarOwner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец Машины')),
            ],
        ),
    ]
